#
# Install Homebrew
#   ruby -e "$(curl -fsSL https://raw.github.com/Homebrew/homebrew/go/install)"
#
# Set brew-cask options
#   export HOMEBREW_CASK_OPTS="--appdir=/Applications --caskroom=/usr/local/Caskroom"
#
# Let's install softwares!
#   brew bundle
#


# Make sure using latest Homebrew
update || true

# Update already-installed formula
upgrade || true

# Add Repository
#tap homebrew/versions || true
tap homebrew/binary || true
tap caskroom/cask || true

# Packages for develop
install zsh || true
install git || true
install tig || true
install vim || true

# Packages for ruby
install openssl || true
install readline || true

# Packages for brew-cask
install brew-cask || true

# .dmg from brew-cask
cask install google-chrome || true
cask install iterm2 || true
cask install virtualbox || true
cask install vagrant || true
cask install keyremap4macbook || true
cask install hipchat || true
cask install macvim || true
cask install alfred || true

# Remove outdated versions
cleanup
